backend:
  name: github
  repo: yancasale/galeria-do-yan
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "works"
    label: "Obras"
    folder: "src/content/works"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Tipo", name: "type", widget: "select", options: ["foto", "desenho"] }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Imagem", name: "image", widget: "image" }
      - { label: "Descrição", name: "description", widget: "text", required: false }
