backend:
  name: git-gateway
  branch: main

media_folder: "public/images/works"
public_folder: "/images/works"

collections:
  - name: "works"
    label: "Obras"
    folder: "src/content/works"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string", required: false }
      - { label: "Data", name: "date", widget: "datetime", required: false }
      - { label: "Tipo", name: "type", widget: "select", options: ["drawing", "photo"] }
      - { label: "Imagem", name: "cover", widget: "image" }
      - { label: "Descrição", name: "description", widget: "text", required: false }

